export type AsciiItemBase = {
  dec: number;
  symbol: string;
  htmlNumber: string;
  htmlName: string;
  description?: string;
  descriptionChinese?: string;
};

export type AsciiItem = AsciiItemBase & {
  hex: string;
  bin: string;
  oct: string;
  group: AsciiGroup;
};

// cspell:disable
export const asciiListBase: AsciiItemBase[] = [
  {
    dec: 0,
    symbol: "NUL",
    htmlNumber: "&#00;",
    htmlName: "",
    description: "Null character",
    descriptionChinese: "空字符",
  },
  {
    dec: 1,
    symbol: "SOH",
    htmlNumber: "&#01;",
    htmlName: "",
    description: "Start of Heading",
    descriptionChinese: "标题开始",
  },
  {
    dec: 2,
    symbol: "STX",
    htmlNumber: "&#02;",
    htmlName: "",
    description: "Start of Text",
    descriptionChinese: "正文开始",
  },
  {
    dec: 3,
    symbol: "ETX",
    htmlNumber: "&#03;",
    htmlName: "",
    description: "End of Text",
    descriptionChinese: "正文结束",
  },
  {
    dec: 4,
    symbol: "EOT",
    htmlNumber: "&#04;",
    htmlName: "",
    description: "End of Transmission",
    descriptionChinese: "传输结束",
  },
  {
    dec: 5,
    symbol: "ENQ",
    htmlNumber: "&#05;",
    htmlName: "",
    description: "Enquiry",
    descriptionChinese: "询问",
  },
  {
    dec: 6,
    symbol: "ACK",
    htmlNumber: "&#06;",
    htmlName: "",
    description: "Acknowledge",
    descriptionChinese: "确认",
  },
  {
    dec: 7,
    symbol: "BEL",
    htmlNumber: "&#07;",
    htmlName: "",
    description: "Bell, Alert",
    descriptionChinese: "铃声，警报",
  },
  {
    dec: 8,
    symbol: "BS",
    htmlNumber: "&#08;",
    htmlName: "",
    description: "Backspace",
    descriptionChinese: "退格",
  },
  {
    dec: 9,
    symbol: "HT",
    htmlNumber: "&#09;",
    htmlName: "",
    description: "Horizontal Tab",
    descriptionChinese: "水平制表符",
  },
  {
    dec: 10,
    symbol: "LF",
    htmlNumber: "&#10;",
    htmlName: "",
    description: "Line Feed",
    descriptionChinese: "换行",
  },
  {
    dec: 11,
    symbol: "VT",
    htmlNumber: "&#11;",
    htmlName: "",
    description: "Vertical Tabulation",
    descriptionChinese: "垂直制表符",
  },
  {
    dec: 12,
    symbol: "FF",
    htmlNumber: "&#12;",
    htmlName: "",
    description: "Form Feed",
    descriptionChinese: "换页",
  },
  {
    dec: 13,
    symbol: "CR",
    htmlNumber: "&#13;",
    htmlName: "",
    description: "Carriage Return",
    descriptionChinese: "回车",
  },
  {
    dec: 14,
    symbol: "SO",
    htmlNumber: "&#14;",
    htmlName: "",
    description: "Shift Out",
    descriptionChinese: "移出",
  },
  {
    dec: 15,
    symbol: "SI",
    htmlNumber: "&#15;",
    htmlName: "",
    description: "Shift In",
    descriptionChinese: "移入",
  },
  {
    dec: 16,
    symbol: "DLE",
    htmlNumber: "&#16;",
    htmlName: "",
    description: "Data Link Escape",
    descriptionChinese: "数据链路转义",
  },
  {
    dec: 17,
    symbol: "DC1",
    htmlNumber: "&#17;",
    htmlName: "",
    description: "Device Control One (XON)",
    descriptionChinese: "设备控制一 (XON)",
  },
  {
    dec: 18,
    symbol: "DC2",
    htmlNumber: "&#18;",
    htmlName: "",
    description: "Device Control Two",
    descriptionChinese: "设备控制二",
  },
  {
    dec: 19,
    symbol: "DC3",
    htmlNumber: "&#19;",
    htmlName: "",
    description: "Device Control Three (XOFF)",
    descriptionChinese: "设备控制三 (XOFF)",
  },
  {
    dec: 20,
    symbol: "DC4",
    htmlNumber: "&#20;",
    htmlName: "",
    description: "Device Control Four",
    descriptionChinese: "设备控制四",
  },
  {
    dec: 21,
    symbol: "NAK",
    htmlNumber: "&#21;",
    htmlName: "",
    description: "Negative Acknowledge",
    descriptionChinese: "否定确认",
  },
  {
    dec: 22,
    symbol: "SYN",
    htmlNumber: "&#22;",
    htmlName: "",
    description: "Synchronous Idle",
    descriptionChinese: "同步空闲",
  },
  {
    dec: 23,
    symbol: "ETB",
    htmlNumber: "&#23;",
    htmlName: "",
    description: "End of Transmission Block",
    descriptionChinese: "传输块结束",
  },
  {
    dec: 24,
    symbol: "CAN",
    htmlNumber: "&#24;",
    htmlName: "",
    description: "Cancel",
    descriptionChinese: "取消",
  },
  {
    dec: 25,
    symbol: "EM",
    htmlNumber: "&#25;",
    htmlName: "",
    description: "End of medium",
    descriptionChinese: "介质结束",
  },
  {
    dec: 26,
    symbol: "SUB",
    htmlNumber: "&#26;",
    htmlName: "",
    description: "Substitute",
    descriptionChinese: "替换",
  },
  {
    dec: 27,
    symbol: "ESC",
    htmlNumber: "&#27;",
    htmlName: "",
    description: "Escape",
    descriptionChinese: "转义",
  },
  {
    dec: 28,
    symbol: "FS",
    htmlNumber: "&#28;",
    htmlName: "",
    description: "File Separator",
    descriptionChinese: "文件分隔符",
  },
  {
    dec: 29,
    symbol: "GS",
    htmlNumber: "&#29;",
    htmlName: "",
    description: "Group Separator",
    descriptionChinese: "组分隔符",
  },
  {
    dec: 30,
    symbol: "RS",
    htmlNumber: "&#30;",
    htmlName: "",
    description: "Record Separator",
    descriptionChinese: "记录分隔符",
  },
  {
    dec: 31,
    symbol: "US",
    htmlNumber: "&#31;",
    htmlName: "",
    description: "Unit Separator",
    descriptionChinese: "单元分隔符",
  },
  {
    dec: 32,
    symbol: "SP",
    htmlNumber: "&#32;",
    htmlName: "",
    description: "Space",
    descriptionChinese: "空格",
  },
  {
    dec: 33,
    symbol: "!",
    htmlNumber: "&#33;",
    htmlName: "&excl;",
    description: "Exclamation mark",
    descriptionChinese: "感叹号",
  },
  {
    dec: 34,
    symbol: '"',
    htmlNumber: "&#34;",
    htmlName: "&quot;",
    description: "Double quotes (or speech marks)",
    descriptionChinese: "双引号",
  },
  {
    dec: 35,
    symbol: "#",
    htmlNumber: "&#35;",
    htmlName: "&num;",
    description: "Number sign",
    descriptionChinese: "井号",
  },
  {
    dec: 36,
    symbol: "$",
    htmlNumber: "&#36;",
    htmlName: "&dollar;",
    description: "Dollar",
    descriptionChinese: "美元符号",
  },
  {
    dec: 37,
    symbol: "%",
    htmlNumber: "&#37;",
    htmlName: "&percnt;",
    description: "Per cent sign",
    descriptionChinese: "百分号",
  },
  {
    dec: 38,
    symbol: "&",
    htmlNumber: "&#38;",
    htmlName: "&amp;",
    description: "Ampersand",
    descriptionChinese: "和号",
  },
  {
    dec: 39,
    symbol: "'",
    htmlNumber: "&#39;",
    htmlName: "&apos;",
    description: "Single quote",
    descriptionChinese: "单引号",
  },
  {
    dec: 40,
    symbol: "(",
    htmlNumber: "&#40;",
    htmlName: "&lparen;",
    description: "Open parenthesis (or open bracket)",
    descriptionChinese: "左括号",
  },
  {
    dec: 41,
    symbol: ")",
    htmlNumber: "&#41;",
    htmlName: "&rparen;",
    description: "Close parenthesis (or close bracket)",
    descriptionChinese: "右括号",
  },
  {
    dec: 42,
    symbol: "*",
    htmlNumber: "&#42;",
    htmlName: "&ast;",
    description: "Asterisk",
    descriptionChinese: "星号",
  },
  {
    dec: 43,
    symbol: "+",
    htmlNumber: "&#43;",
    htmlName: "&plus;",
    description: "Plus",
    descriptionChinese: "加号",
  },
  {
    dec: 44,
    symbol: ",",
    htmlNumber: "&#44;",
    htmlName: "&comma;",
    description: "Comma",
    descriptionChinese: "逗号",
  },
  {
    dec: 45,
    symbol: "-",
    htmlNumber: "&#45;",
    htmlName: "",
    description: "Hyphen-minus",
    descriptionChinese: "连字符",
  },
  {
    dec: 46,
    symbol: ".",
    htmlNumber: "&#46;",
    htmlName: "&period;",
    description: "Period, dot or full stop",
    descriptionChinese: "句号",
  },
  {
    dec: 47,
    symbol: "/",
    htmlNumber: "&#47;",
    htmlName: "&sol;",
    description: "Slash or divide",
    descriptionChinese: "斜杠",
  },
  {
    dec: 48,
    symbol: "0",
    htmlNumber: "&#48;",
    htmlName: "",
    description: "Zero",
    descriptionChinese: "零",
  },
  {
    dec: 49,
    symbol: "1",
    htmlNumber: "&#49;",
    htmlName: "",
    description: "One",
    descriptionChinese: "一",
  },
  {
    dec: 50,
    symbol: "2",
    htmlNumber: "&#50;",
    htmlName: "",
    description: "Two",
    descriptionChinese: "二",
  },
  {
    dec: 51,
    symbol: "3",
    htmlNumber: "&#51;",
    htmlName: "",
    description: "Three",
    descriptionChinese: "三",
  },
  {
    dec: 52,
    symbol: "4",
    htmlNumber: "&#52;",
    htmlName: "",
    description: "Four",
    descriptionChinese: "四",
  },
  {
    dec: 53,
    symbol: "5",
    htmlNumber: "&#53;",
    htmlName: "",
    description: "Five",
    descriptionChinese: "五",
  },
  {
    dec: 54,
    symbol: "6",
    htmlNumber: "&#54;",
    htmlName: "",
    description: "Six",
    descriptionChinese: "六",
  },
  {
    dec: 55,
    symbol: "7",
    htmlNumber: "&#55;",
    htmlName: "",
    description: "Seven",
    descriptionChinese: "七",
  },
  {
    dec: 56,
    symbol: "8",
    htmlNumber: "&#56;",
    htmlName: "",
    description: "Eight",
    descriptionChinese: "八",
  },
  {
    dec: 57,
    symbol: "9",
    htmlNumber: "&#57;",
    htmlName: "",
    description: "Nine",
    descriptionChinese: "九",
  },
  {
    dec: 58,
    symbol: ":",
    htmlNumber: "&#58;",
    htmlName: "&colon;",
    description: "Colon",
    descriptionChinese: "冒号",
  },
  {
    dec: 59,
    symbol: ";",
    htmlNumber: "&#59;",
    htmlName: "&semi;",
    description: "Semicolon",
    descriptionChinese: "分号",
  },
  {
    dec: 60,
    symbol: "<",
    htmlNumber: "&#60;",
    htmlName: "&lt;",
    description: "Less than (or open angled bracket)",
    descriptionChinese: "小于号",
  },
  {
    dec: 61,
    symbol: "=",
    htmlNumber: "&#61;",
    htmlName: "&equals;",
    description: "Equals",
    descriptionChinese: "等号",
  },
  {
    dec: 62,
    symbol: ">",
    htmlNumber: "&#62;",
    htmlName: "&gt;",
    description: "Greater than (or close angled bracket)",
    descriptionChinese: "大于号",
  },
  {
    dec: 63,
    symbol: "?",
    htmlNumber: "&#63;",
    htmlName: "&quest;",
    description: "Question mark",
    descriptionChinese: "问号",
  },
  {
    dec: 64,
    symbol: "@",
    htmlNumber: "&#64;",
    htmlName: "&commat;",
    description: "At sign",
    descriptionChinese: "艾特符号",
  },
  {
    dec: 65,
    symbol: "A",
    htmlNumber: "&#65;",
    htmlName: "",
    description: "Uppercase A",
    descriptionChinese: "大写字母A",
  },
  {
    dec: 66,
    symbol: "B",
    htmlNumber: "&#66;",
    htmlName: "",
    description: "Uppercase B",
    descriptionChinese: "大写字母B",
  },
  {
    dec: 67,
    symbol: "C",
    htmlNumber: "&#67;",
    htmlName: "",
    description: "Uppercase C",
    descriptionChinese: "大写字母C",
  },
  {
    dec: 68,
    symbol: "D",
    htmlNumber: "&#68;",
    htmlName: "",
    description: "Uppercase D",
    descriptionChinese: "大写字母D",
  },
  {
    dec: 69,
    symbol: "E",
    htmlNumber: "&#69;",
    htmlName: "",
    description: "Uppercase E",
    descriptionChinese: "大写字母E",
  },
  {
    dec: 70,
    symbol: "F",
    htmlNumber: "&#70;",
    htmlName: "",
    description: "Uppercase F",
    descriptionChinese: "大写字母F",
  },
  {
    dec: 71,
    symbol: "G",
    htmlNumber: "&#71;",
    htmlName: "",
    description: "Uppercase G",
    descriptionChinese: "大写字母G",
  },
  {
    dec: 72,
    symbol: "H",
    htmlNumber: "&#72;",
    htmlName: "",
    description: "Uppercase H",
    descriptionChinese: "大写字母H",
  },
  {
    dec: 73,
    symbol: "I",
    htmlNumber: "&#73;",
    htmlName: "",
    description: "Uppercase I",
    descriptionChinese: "大写字母I",
  },
  {
    dec: 74,
    symbol: "J",
    htmlNumber: "&#74;",
    htmlName: "",
    description: "Uppercase J",
    descriptionChinese: "大写字母J",
  },
  {
    dec: 75,
    symbol: "K",
    htmlNumber: "&#75;",
    htmlName: "",
    description: "Uppercase K",
    descriptionChinese: "大写字母K",
  },
  {
    dec: 76,
    symbol: "L",
    htmlNumber: "&#76;",
    htmlName: "",
    description: "Uppercase L",
    descriptionChinese: "大写字母L",
  },
  {
    dec: 77,
    symbol: "M",
    htmlNumber: "&#77;",
    htmlName: "",
    description: "Uppercase M",
    descriptionChinese: "大写字母M",
  },
  {
    dec: 78,
    symbol: "N",
    htmlNumber: "&#78;",
    htmlName: "",
    description: "Uppercase N",
    descriptionChinese: "大写字母N",
  },
  {
    dec: 79,
    symbol: "O",
    htmlNumber: "&#79;",
    htmlName: "",
    description: "Uppercase O",
    descriptionChinese: "大写字母O",
  },
  {
    dec: 80,
    symbol: "P",
    htmlNumber: "&#80;",
    htmlName: "",
    description: "Uppercase P",
    descriptionChinese: "大写字母P",
  },
  {
    dec: 81,
    symbol: "Q",
    htmlNumber: "&#81;",
    htmlName: "",
    description: "Uppercase Q",
    descriptionChinese: "大写字母Q",
  },
  {
    dec: 82,
    symbol: "R",
    htmlNumber: "&#82;",
    htmlName: "",
    description: "Uppercase R",
    descriptionChinese: "大写字母R",
  },
  {
    dec: 83,
    symbol: "S",
    htmlNumber: "&#83;",
    htmlName: "",
    description: "Uppercase S",
    descriptionChinese: "大写字母S",
  },
  {
    dec: 84,
    symbol: "T",
    htmlNumber: "&#84;",
    htmlName: "",
    description: "Uppercase T",
    descriptionChinese: "大写字母T",
  },
  {
    dec: 85,
    symbol: "U",
    htmlNumber: "&#85;",
    htmlName: "",
    description: "Uppercase U",
    descriptionChinese: "大写字母U",
  },
  {
    dec: 86,
    symbol: "V",
    htmlNumber: "&#86;",
    htmlName: "",
    description: "Uppercase V",
    descriptionChinese: "大写字母V",
  },
  {
    dec: 87,
    symbol: "W",
    htmlNumber: "&#87;",
    htmlName: "",
    description: "Uppercase W",
    descriptionChinese: "大写字母W",
  },
  {
    dec: 88,
    symbol: "X",
    htmlNumber: "&#88;",
    htmlName: "",
    description: "Uppercase X",
    descriptionChinese: "大写字母X",
  },
  {
    dec: 89,
    symbol: "Y",
    htmlNumber: "&#89;",
    htmlName: "",
    description: "Uppercase Y",
    descriptionChinese: "大写字母Y",
  },
  {
    dec: 90,
    symbol: "Z",
    htmlNumber: "&#90;",
    htmlName: "",
    description: "Uppercase Z",
    descriptionChinese: "大写字母Z",
  },
  {
    dec: 91,
    symbol: "[",
    htmlNumber: "&#91;",
    htmlName: "&lsqb;",
    description: "Opening bracket",
    descriptionChinese: "左方括号",
  },
  {
    dec: 92,
    symbol: "\\",
    htmlNumber: "&#92;",
    htmlName: "&bsol;",
    description: "Backslash",
    descriptionChinese: "反斜杠",
  },
  {
    dec: 93,
    symbol: "]",
    htmlNumber: "&#93;",
    htmlName: "&rsqb;",
    description: "Closing bracket",
    descriptionChinese: "右方括号",
  },
  {
    dec: 94,
    symbol: "^",
    htmlNumber: "&#94;",
    htmlName: "&Hat;",
    description: "Caret - circumflex",
    descriptionChinese: "插入符号",
  },
  {
    dec: 95,
    symbol: "_",
    htmlNumber: "&#95;",
    htmlName: "&lowbar;",
    description: "Underscore",
    descriptionChinese: "下划线",
  },
  {
    dec: 96,
    symbol: "`",
    htmlNumber: "&#96;",
    htmlName: "&grave;",
    description: "Grave accent",
    descriptionChinese: "重音符",
  },
  {
    dec: 97,
    symbol: "a",
    htmlNumber: "&#97;",
    htmlName: "",
    description: "Lowercase a",
    descriptionChinese: "小写字母a",
  },
  {
    dec: 98,
    symbol: "b",
    htmlNumber: "&#98;",
    htmlName: "",
    description: "Lowercase b",
    descriptionChinese: "小写字母b",
  },
  {
    dec: 99,
    symbol: "c",
    htmlNumber: "&#99;",
    htmlName: "",
    description: "Lowercase c",
    descriptionChinese: "小写字母c",
  },
  {
    dec: 100,
    symbol: "d",
    htmlNumber: "&#100;",
    htmlName: "",
    description: "Lowercase d",
    descriptionChinese: "小写字母d",
  },
  {
    dec: 101,
    symbol: "e",
    htmlNumber: "&#101;",
    htmlName: "",
    description: "Lowercase e",
    descriptionChinese: "小写字母e",
  },
  {
    dec: 102,
    symbol: "f",
    htmlNumber: "&#102;",
    htmlName: "",
    description: "Lowercase f",
    descriptionChinese: "小写字母f",
  },
  {
    dec: 103,
    symbol: "g",
    htmlNumber: "&#103;",
    htmlName: "",
    description: "Lowercase g",
    descriptionChinese: "小写字母g",
  },
  {
    dec: 104,
    symbol: "h",
    htmlNumber: "&#104;",
    htmlName: "",
    description: "Lowercase h",
    descriptionChinese: "小写字母h",
  },
  {
    dec: 105,
    symbol: "i",
    htmlNumber: "&#105;",
    htmlName: "",
    description: "Lowercase i",
    descriptionChinese: "小写字母i",
  },
  {
    dec: 106,
    symbol: "j",
    htmlNumber: "&#106;",
    htmlName: "",
    description: "Lowercase j",
    descriptionChinese: "小写字母j",
  },
  {
    dec: 107,
    symbol: "k",
    htmlNumber: "&#107;",
    htmlName: "",
    description: "Lowercase k",
    descriptionChinese: "小写字母k",
  },
  {
    dec: 108,
    symbol: "l",
    htmlNumber: "&#108;",
    htmlName: "",
    description: "Lowercase l",
    descriptionChinese: "小写字母l",
  },
  {
    dec: 109,
    symbol: "m",
    htmlNumber: "&#109;",
    htmlName: "",
    description: "Lowercase m",
    descriptionChinese: "小写字母m",
  },
  {
    dec: 110,
    symbol: "n",
    htmlNumber: "&#110;",
    htmlName: "",
    description: "Lowercase n",
    descriptionChinese: "小写字母n",
  },
  {
    dec: 111,
    symbol: "o",
    htmlNumber: "&#111;",
    htmlName: "",
    description: "Lowercase o",
    descriptionChinese: "小写字母o",
  },
  {
    dec: 112,
    symbol: "p",
    htmlNumber: "&#112;",
    htmlName: "",
    description: "Lowercase p",
    descriptionChinese: "小写字母p",
  },
  {
    dec: 113,
    symbol: "q",
    htmlNumber: "&#113;",
    htmlName: "",
    description: "Lowercase q",
    descriptionChinese: "小写字母q",
  },
  {
    dec: 114,
    symbol: "r",
    htmlNumber: "&#114;",
    htmlName: "",
    description: "Lowercase r",
    descriptionChinese: "小写字母r",
  },
  {
    dec: 115,
    symbol: "s",
    htmlNumber: "&#115;",
    htmlName: "",
    description: "Lowercase s",
    descriptionChinese: "小写字母s",
  },
  {
    dec: 116,
    symbol: "t",
    htmlNumber: "&#116;",
    htmlName: "",
    description: "Lowercase t",
    descriptionChinese: "小写字母t",
  },
  {
    dec: 117,
    symbol: "u",
    htmlNumber: "&#117;",
    htmlName: "",
    description: "Lowercase u",
    descriptionChinese: "小写字母u",
  },
  {
    dec: 118,
    symbol: "v",
    htmlNumber: "&#118;",
    htmlName: "",
    description: "Lowercase v",
    descriptionChinese: "小写字母v",
  },
  {
    dec: 119,
    symbol: "w",
    htmlNumber: "&#119;",
    htmlName: "",
    description: "Lowercase w",
    descriptionChinese: "小写字母w",
  },
  {
    dec: 120,
    symbol: "x",
    htmlNumber: "&#120;",
    htmlName: "",
    description: "Lowercase x",
    descriptionChinese: "小写字母x",
  },
  {
    dec: 121,
    symbol: "y",
    htmlNumber: "&#121;",
    htmlName: "",
    description: "Lowercase y",
    descriptionChinese: "小写字母y",
  },
  {
    dec: 122,
    symbol: "z",
    htmlNumber: "&#122;",
    htmlName: "",
    description: "Lowercase z",
    descriptionChinese: "小写字母z",
  },
  {
    dec: 123,
    symbol: "{",
    htmlNumber: "&#123;",
    htmlName: "&lcub;",
    description: "Opening brace",
    descriptionChinese: "左大括号",
  },
  {
    dec: 124,
    symbol: "|",
    htmlNumber: "&#124;",
    htmlName: "&verbar;",
    description: "Vertical bar",
    descriptionChinese: "竖线",
  },
  {
    dec: 125,
    symbol: "}",
    htmlNumber: "&#125;",
    htmlName: "&rcub;",
    description: "Closing brace",
    descriptionChinese: "右大括号",
  },
  {
    dec: 126,
    symbol: "~",
    htmlNumber: "&#126;",
    htmlName: "&tilde;",
    description: "Equivalency sign - tilde",
    descriptionChinese: "波浪号",
  },
  {
    dec: 127,
    symbol: "DEL",
    htmlNumber: "&#127;",
    htmlName: "",
    description: "Delete",
    descriptionChinese: "删除",
  },
  {
    dec: 128,
    symbol: "€",
    htmlNumber: "&#8364;",
    htmlName: "&euro;",
    description: "Euro sign",
    descriptionChinese: "欧元符号",
  },
  {
    dec: 129,
    symbol: "",
    htmlNumber: "",
    htmlName: "",
    description: "Unused",
    descriptionChinese: "未使用",
  },
  {
    dec: 130,
    symbol: "‚",
    htmlNumber: "&#130;",
    htmlName: "&sbquo;",
    description: "Single low-9 quotation mark",
    descriptionChinese: "单低9引号",
  },
  {
    dec: 131,
    symbol: "ƒ",
    htmlNumber: "&#131;",
    htmlName: "&fnof;",
    description: "Latin small letter f with hook",
    descriptionChinese: "带钩的小写字母f",
  },
  {
    dec: 132,
    symbol: "„",
    htmlNumber: "&#132;",
    htmlName: "&bdquo;",
    description: "Double low-9 quotation mark",
    descriptionChinese: "双低9引号",
  },
  {
    dec: 133,
    symbol: "…",
    htmlNumber: "&#133;",
    htmlName: "&hellip;",
    description: "Horizontal ellipsis",
    descriptionChinese: "省略号",
  },
  {
    dec: 134,
    symbol: "†",
    htmlNumber: "&#134;",
    htmlName: "&dagger;",
    description: "Dagger",
    descriptionChinese: "匕首",
  },
  {
    dec: 135,
    symbol: "‡",
    htmlNumber: "&#135;",
    htmlName: "&Dagger;",
    description: "Double dagger",
    descriptionChinese: "双匕首",
  },
  {
    dec: 136,
    symbol: "ˆ",
    htmlNumber: "&#136;",
    htmlName: "&circ;",
    description: "Modifier letter circumflex accent",
    descriptionChinese: "变音符号",
  },
  {
    dec: 137,
    symbol: "‰",
    htmlNumber: "&#137;",
    htmlName: "&permil;",
    description: "Per mille sign",
    descriptionChinese: "千分号",
  },
  {
    dec: 138,
    symbol: "Š",
    htmlNumber: "&#138;",
    htmlName: "&Scaron;",
    description: "Latin capital letter S with caron",
    descriptionChinese: "带抑扬符的大写字母S",
  },
  {
    dec: 139,
    symbol: "‹",
    htmlNumber: "&#139;",
    htmlName: "&lsaquo;",
    description: "Single left-pointing angle quotation",
    descriptionChinese: "单左尖括号",
  },
  {
    dec: 140,
    symbol: "Œ",
    htmlNumber: "&#140;",
    htmlName: "&OElig;",
    description: "Latin capital ligature OE",
    descriptionChinese: "拉丁大写字母连字OE",
  },
  {
    dec: 141,
    symbol: "",
    htmlNumber: "",
    htmlName: "",
    description: "Unused",
    descriptionChinese: "未使用",
  },
  {
    dec: 142,
    symbol: "Ž",
    htmlNumber: "&#142;",
    htmlName: "&Zcaron;",
    description: "Latin capital letter Z with caron",
    descriptionChinese: "带抑扬符的大写字母Z",
  },
  {
    dec: 143,
    symbol: "",
    htmlNumber: "",
    htmlName: "",
    description: "Unused",
    descriptionChinese: "未使用",
  },
  {
    dec: 144,
    symbol: "",
    htmlNumber: "",
    htmlName: "",
    description: "Unused",
    descriptionChinese: "未使用",
  },
  {
    dec: 145,
    symbol: "‘",
    htmlNumber: "&#145;",
    htmlName: "&lsquo;",
    description: "Left single quotation mark",
    descriptionChinese: "左单引号",
  },
  {
    dec: 146,
    symbol: "’",
    htmlNumber: "&#146;",
    htmlName: "&rsquo;",
    description: "Right single quotation mark",
    descriptionChinese: "右单引号",
  },
  {
    dec: 147,
    symbol: "“",
    htmlNumber: "&#147;",
    htmlName: "&ldquo;",
    description: "Left double quotation mark",
    descriptionChinese: "左双引号",
  },
  {
    dec: 148,
    symbol: "”",
    htmlNumber: "&#148;",
    htmlName: "&rdquo;",
    description: "Right double quotation mark",
    descriptionChinese: "右双引号",
  },
  {
    dec: 149,
    symbol: "•",
    htmlNumber: "&#149;",
    htmlName: "&bull;",
    description: "Bullet",
    descriptionChinese: "项目符号",
  },
  {
    dec: 150,
    symbol: "–",
    htmlNumber: "&#150;",
    htmlName: "&ndash;",
    description: "En dash",
    descriptionChinese: "短破折号",
  },
  {
    dec: 151,
    symbol: "—",
    htmlNumber: "&#151;",
    htmlName: "&mdash;",
    description: "Em dash",
    descriptionChinese: "长破折号",
  },
  {
    dec: 152,
    symbol: "˜",
    htmlNumber: "&#152;",
    htmlName: "&tilde;",
    description: "Small tilde",
    descriptionChinese: "小波浪号",
  },
  {
    dec: 153,
    symbol: "™",
    htmlNumber: "&#153;",
    htmlName: "&trade;",
    description: "Trade mark sign",
    descriptionChinese: "商标符号",
  },
  {
    dec: 154,
    symbol: "š",
    htmlNumber: "&#154;",
    htmlName: "&scaron;",
    description: "Latin small letter S with caron",
    descriptionChinese: "带抑扬符的小写字母S",
  },
  {
    dec: 155,
    symbol: "›",
    htmlNumber: "&#155;",
    htmlName: "&rsaquo;",
    description: "Single right-pointing angle quotation mark",
    descriptionChinese: "单右尖括号",
  },
  {
    dec: 156,
    symbol: "œ",
    htmlNumber: "&#156;",
    htmlName: "&oelig;",
    description: "Latin small ligature oe",
    descriptionChinese: "拉丁小写字母连字oe",
  },
  {
    dec: 157,
    symbol: "",
    htmlNumber: "",
    htmlName: "",
    description: "Unused",
    descriptionChinese: "未使用",
  },
  {
    dec: 158,
    symbol: "ž",
    htmlNumber: "&#158;",
    htmlName: "&zcaron;",
    description: "Latin small letter z with caron",
    descriptionChinese: "带抑扬符的小写字母z",
  },
  {
    dec: 159,
    symbol: "Ÿ",
    htmlNumber: "&#159;",
    htmlName: "&Yuml;",
    description: "Latin capital letter Y with diaeresis",
    descriptionChinese: "带分音符的大写字母Y",
  },
  {
    dec: 160,
    symbol: "NBSP",
    htmlNumber: "&#160;",
    htmlName: "&nbsp;",
    description: "Non-breaking space",
    descriptionChinese: "不间断空格",
  },
  {
    dec: 161,
    symbol: "¡",
    htmlNumber: "&#161;",
    htmlName: "&iexcl;",
    description: "Inverted exclamation mark",
    descriptionChinese: "倒感叹号",
  },
  {
    dec: 162,
    symbol: "¢",
    htmlNumber: "&#162;",
    htmlName: "&cent;",
    description: "Cent sign",
    descriptionChinese: "分号",
  },
  {
    dec: 163,
    symbol: "£",
    htmlNumber: "&#163;",
    htmlName: "&pound;",
    description: "Pound sign",
    descriptionChinese: "英镑符号",
  },
  {
    dec: 164,
    symbol: "¤",
    htmlNumber: "&#164;",
    htmlName: "&curren;",
    description: "Currency sign",
    descriptionChinese: "货币符号",
  },
  {
    dec: 165,
    symbol: "¥",
    htmlNumber: "&#165;",
    htmlName: "&yen;",
    description: "Yen sign",
    descriptionChinese: "日元符号",
  },
  {
    dec: 166,
    symbol: "¦",
    htmlNumber: "&#166;",
    htmlName: "&brvbar;",
    description: "Pipe, broken vertical bar",
    descriptionChinese: "竖线，断竖线",
  },
  {
    dec: 167,
    symbol: "§",
    htmlNumber: "&#167;",
    htmlName: "&sect;",
    description: "Section sign",
    descriptionChinese: "章节符号",
  },
  {
    dec: 168,
    symbol: "¨",
    htmlNumber: "&#168;",
    htmlName: "&uml;",
    description: "Spacing diaeresis - umlaut",
    descriptionChinese: "分音符",
  },
  {
    dec: 169,
    symbol: "©",
    htmlNumber: "&#169;",
    htmlName: "&copy;",
    description: "Copyright sign",
    descriptionChinese: "版权符号",
  },
  {
    dec: 170,
    symbol: "ª",
    htmlNumber: "&#170;",
    htmlName: "&ordf;",
    description: "Feminine ordinal indicator",
    descriptionChinese: "阴性序数符号",
  },
  {
    dec: 171,
    symbol: "«",
    htmlNumber: "&#171;",
    htmlName: "&laquo;",
    description: "Left double angle quotes",
    descriptionChinese: "左双尖括号",
  },
  {
    dec: 172,
    symbol: "¬",
    htmlNumber: "&#172;",
    htmlName: "&not;",
    description: "Negation",
    descriptionChinese: "否定",
  },
  {
    dec: 173,
    symbol: "­SHY",
    htmlNumber: "&#173;",
    htmlName: "&shy;",
    description: "Soft hyphen",
    descriptionChinese: "软连字符",
  },
  {
    dec: 174,
    symbol: "®",
    htmlNumber: "&#174;",
    htmlName: "&reg;",
    description: "Registered trade mark sign",
    descriptionChinese: "注册商标符号",
  },
  {
    dec: 175,
    symbol: "¯",
    htmlNumber: "&#175;",
    htmlName: "&macr;",
    description: "Spacing macron - overline",
    descriptionChinese: "长音符",
  },
  {
    dec: 176,
    symbol: "°",
    htmlNumber: "&#176;",
    htmlName: "&deg;",
    description: "Degree sign",
    descriptionChinese: "度数符号",
  },
  {
    dec: 177,
    symbol: "±",
    htmlNumber: "&#177;",
    htmlName: "&plusmn;",
    description: "Plus-or-minus sign",
    descriptionChinese: "正负号",
  },
  {
    dec: 178,
    symbol: "²",
    htmlNumber: "&#178;",
    htmlName: "&sup2;",
    description: "Superscript two - squared",
    descriptionChinese: "上标二",
  },
  {
    dec: 179,
    symbol: "³",
    htmlNumber: "&#179;",
    htmlName: "&sup3;",
    description: "Superscript three - cubed",
    descriptionChinese: "上标三",
  },
  {
    dec: 180,
    symbol: "´",
    htmlNumber: "&#180;",
    htmlName: "&acute;",
    description: "Acute accent - spacing acute",
    descriptionChinese: "尖音符",
  },
  {
    dec: 181,
    symbol: "µ",
    htmlNumber: "&#181;",
    htmlName: "&micro;",
    description: "Micro sign",
    descriptionChinese: "微符号",
  },
  {
    dec: 182,
    symbol: "¶",
    htmlNumber: "&#182;",
    htmlName: "&para;",
    description: "Pilcrow sign - paragraph sign",
    descriptionChinese: "段落符号",
  },
  {
    dec: 183,
    symbol: "·",
    htmlNumber: "&#183;",
    htmlName: "&middot;",
    description: "Middle dot - Georgian comma",
    descriptionChinese: "中点",
  },
  {
    dec: 184,
    symbol: "¸",
    htmlNumber: "&#184;",
    htmlName: "&cedil;",
    description: "Spacing cedilla",
    descriptionChinese: "分音符",
  },
  {
    dec: 185,
    symbol: "¹",
    htmlNumber: "&#185;",
    htmlName: "&sup1;",
    description: "Superscript one",
    descriptionChinese: "上标一",
  },
  {
    dec: 186,
    symbol: "º",
    htmlNumber: "&#186;",
    htmlName: "&ordm;",
    description: "Masculine ordinal indicator",
    descriptionChinese: "阳性序数符号",
  },
  {
    dec: 187,
    symbol: "»",
    htmlNumber: "&#187;",
    htmlName: "&raquo;",
    description: "Right double angle quotes",
    descriptionChinese: "右双尖括号",
  },
  {
    dec: 188,
    symbol: "¼",
    htmlNumber: "&#188;",
    htmlName: "&frac14;",
    description: "Fraction one quarter",
    descriptionChinese: "四分之一",
  },
  {
    dec: 189,
    symbol: "½",
    htmlNumber: "&#189;",
    htmlName: "&frac12;",
    description: "Fraction one half",
    descriptionChinese: "二分之一",
  },
  {
    dec: 190,
    symbol: "¾",
    htmlNumber: "&#190;",
    htmlName: "&frac34;",
    description: "Fraction three quarters",
    descriptionChinese: "四分之三",
  },
  {
    dec: 191,
    symbol: "¿",
    htmlNumber: "&#191;",
    htmlName: "&iquest;",
    description: "Inverted question mark",
    descriptionChinese: "倒问号",
  },
  {
    dec: 192,
    symbol: "À",
    htmlNumber: "&#192;",
    htmlName: "&Agrave;",
    description: "Latin capital letter A with grave",
    descriptionChinese: "带重音符的大写字母A",
  },
  {
    dec: 193,
    symbol: "Á",
    htmlNumber: "&#193;",
    htmlName: "&Aacute;",
    description: "Latin capital letter A with acute",
    descriptionChinese: "带尖音符的大写字母A",
  },
  {
    dec: 194,
    symbol: "Â",
    htmlNumber: "&#194;",
    htmlName: "&Acirc;",
    description: "Latin capital letter A with circumflex",
    descriptionChinese: "带抑扬符的大写字母A",
  },
  {
    dec: 195,
    symbol: "Ã",
    htmlNumber: "&#195;",
    htmlName: "&Atilde;",
    description: "Latin capital letter A with tilde",
    descriptionChinese: "带波浪号的大写字母A",
  },
  {
    dec: 196,
    symbol: "Ä",
    htmlNumber: "&#196;",
    htmlName: "&Auml;",
    description: "Latin capital letter A with diaeresis",
    descriptionChinese: "带分音符的大写字母A",
  },
  {
    dec: 197,
    symbol: "Å",
    htmlNumber: "&#197;",
    htmlName: "&Aring;",
    description: "Latin capital letter A with ring above",
    descriptionChinese: "带环的大写字母A",
  },
  {
    dec: 198,
    symbol: "Æ",
    htmlNumber: "&#198;",
    htmlName: "&AElig;",
    description: "Latin capital letter AE",
    descriptionChinese: "拉丁大写字母AE",
  },
  {
    dec: 199,
    symbol: "Ç",
    htmlNumber: "&#199;",
    htmlName: "&Ccedil;",
    description: "Latin capital letter C with cedilla",
    descriptionChinese: "带分音符的大写字母C",
  },
  {
    dec: 200,
    symbol: "È",
    htmlNumber: "&#200;",
    htmlName: "&Egrave;",
    description: "Latin capital letter E with grave",
    descriptionChinese: "带重音符的大写字母E",
  },
  {
    dec: 201,
    symbol: "É",
    htmlNumber: "&#201;",
    htmlName: "&Eacute;",
    description: "Latin capital letter E with acute",
    descriptionChinese: "带尖音符的大写字母E",
  },
  {
    dec: 202,
    symbol: "Ê",
    htmlNumber: "&#202;",
    htmlName: "&Ecirc;",
    description: "Latin capital letter E with circumflex",
    descriptionChinese: "带抑扬符的大写字母E",
  },
  {
    dec: 203,
    symbol: "Ë",
    htmlNumber: "&#203;",
    htmlName: "&Euml;",
    description: "Latin capital letter E with diaeresis",
    descriptionChinese: "带分音符的大写字母E",
  },
  {
    dec: 204,
    symbol: "Ì",
    htmlNumber: "&#204;",
    htmlName: "&Igrave;",
    description: "Latin capital letter I with grave",
    descriptionChinese: "带重音符的大写字母I",
  },
  {
    dec: 205,
    symbol: "Í",
    htmlNumber: "&#205;",
    htmlName: "&Iacute;",
    description: "Latin capital letter I with acute",
    descriptionChinese: "带尖音符的大写字母I",
  },
  {
    dec: 206,
    symbol: "Î",
    htmlNumber: "&#206;",
    htmlName: "&Icirc;",
    description: "Latin capital letter I with circumflex",
    descriptionChinese: "带抑扬符的大写字母I",
  },
  {
    dec: 207,
    symbol: "Ï",
    htmlNumber: "&#207;",
    htmlName: "&Iuml;",
    description: "Latin capital letter I with diaeresis",
    descriptionChinese: "带分音符的大写字母I",
  },
  {
    dec: 208,
    symbol: "Ð",
    htmlNumber: "&#208;",
    htmlName: "&ETH;",
    description: "Latin capital letter ETH",
    descriptionChinese: "拉丁大写字母ETH",
  },
  {
    dec: 209,
    symbol: "Ñ",
    htmlNumber: "&#209;",
    htmlName: "&Ntilde;",
    description: "Latin capital letter N with tilde",
    descriptionChinese: "带波浪号的大写字母N",
  },
  {
    dec: 210,
    symbol: "Ò",
    htmlNumber: "&#210;",
    htmlName: "&Ograve;",
    description: "Latin capital letter O with grave",
    descriptionChinese: "带重音符的大写字母O",
  },
  {
    dec: 211,
    symbol: "Ó",
    htmlNumber: "&#211;",
    htmlName: "&Oacute;",
    description: "Latin capital letter O with acute",
    descriptionChinese: "带尖音符的大写字母O",
  },
  {
    dec: 212,
    symbol: "Ô",
    htmlNumber: "&#212;",
    htmlName: "&Ocirc;",
    description: "Latin capital letter O with circumflex",
    descriptionChinese: "带抑扬符的大写字母O",
  },
  {
    dec: 213,
    symbol: "Õ",
    htmlNumber: "&#213;",
    htmlName: "&Otilde;",
    description: "Latin capital letter O with tilde",
    descriptionChinese: "带波浪号的大写字母O",
  },
  {
    dec: 214,
    symbol: "Ö",
    htmlNumber: "&#214;",
    htmlName: "&Ouml;",
    description: "Latin capital letter O with diaeresis",
    descriptionChinese: "带分音符的大写字母O",
  },
  {
    dec: 215,
    symbol: "×",
    htmlNumber: "&#215;",
    htmlName: "&times;",
    description: "Multiplication sign",
    descriptionChinese: "乘号",
  },
  {
    dec: 216,
    symbol: "Ø",
    htmlNumber: "&#216;",
    htmlName: "&Oslash;",
    description: "Latin capital letter O with slash",
    descriptionChinese: "带斜杠的大写字母O",
  },
  {
    dec: 217,
    symbol: "Ù",
    htmlNumber: "&#217;",
    htmlName: "&Ugrave;",
    description: "Latin capital letter U with grave",
    descriptionChinese: "带重音符的大写字母U",
  },
  {
    dec: 218,
    symbol: "Ú",
    htmlNumber: "&#218;",
    htmlName: "&Uacute;",
    description: "Latin capital letter U with acute",
    descriptionChinese: "带尖音符的大写字母U",
  },
  {
    dec: 219,
    symbol: "Û",
    htmlNumber: "&#219;",
    htmlName: "&Ucirc;",
    description: "Latin capital letter U with circumflex",
    descriptionChinese: "带抑扬符的大写字母U",
  },
  {
    dec: 220,
    symbol: "Ü",
    htmlNumber: "&#220;",
    htmlName: "&Uuml;",
    description: "Latin capital letter U with diaeresis",
    descriptionChinese: "带分音符的大写字母U",
  },
  {
    dec: 221,
    symbol: "Ý",
    htmlNumber: "&#221;",
    htmlName: "&Yacute;",
    description: "Latin capital letter Y with acute",
    descriptionChinese: "带尖音符的大写字母Y",
  },
  {
    dec: 222,
    symbol: "Þ",
    htmlNumber: "&#222;",
    htmlName: "&THORN;",
    description: "Latin capital letter THORN",
    descriptionChinese: "拉丁大写字母THORN",
  },
  {
    dec: 223,
    symbol: "ß",
    htmlNumber: "&#223;",
    htmlName: "&szlig;",
    description: "Latin small letter sharp s - ess-zed",
    descriptionChinese: "拉丁小写字母尖音s",
  },
  {
    dec: 224,
    symbol: "à",
    htmlNumber: "&#224;",
    htmlName: "&agrave;",
    description: "Latin small letter a with grave",
    descriptionChinese: "带重音符的小写字母a",
  },
  {
    dec: 225,
    symbol: "á",
    htmlNumber: "&#225;",
    htmlName: "&aacute;",
    description: "Latin small letter a with acute",
    descriptionChinese: "带尖音符的小写字母a",
  },
  {
    dec: 226,
    symbol: "â",
    htmlNumber: "&#226;",
    htmlName: "&acirc;",
    description: "Latin small letter a with circumflex",
    descriptionChinese: "带抑扬符的小写字母a",
  },
  {
    dec: 227,
    symbol: "ã",
    htmlNumber: "&#227;",
    htmlName: "&atilde;",
    description: "Latin small letter a with tilde",
    descriptionChinese: "带波浪号的小写字母a",
  },
  {
    dec: 228,
    symbol: "ä",
    htmlNumber: "&#228;",
    htmlName: "&auml;",
    description: "Latin small letter a with diaeresis",
    descriptionChinese: "带分音符的小写字母a",
  },
  {
    dec: 229,
    symbol: "å",
    htmlNumber: "&#229;",
    htmlName: "&aring;",
    description: "Latin small letter a with ring above",
    descriptionChinese: "带环的小写字母a",
  },
  {
    dec: 230,
    symbol: "æ",
    htmlNumber: "&#230;",
    htmlName: "&aelig;",
    description: "Latin small letter ae",
    descriptionChinese: "拉丁小写字母ae",
  },
  {
    dec: 231,
    symbol: "ç",
    htmlNumber: "&#231;",
    htmlName: "&ccedil;",
    description: "Latin small letter c with cedilla",
    descriptionChinese: "带分音符的小写字母c",
  },
  {
    dec: 232,
    symbol: "è",
    htmlNumber: "&#232;",
    htmlName: "&egrave;",
    description: "Latin small letter e with grave",
    descriptionChinese: "带重音符的小写字母e",
  },
  {
    dec: 233,
    symbol: "é",
    htmlNumber: "&#233;",
    htmlName: "&eacute;",
    description: "Latin small letter e with acute",
    descriptionChinese: "带尖音符的小写字母e",
  },
  {
    dec: 234,
    symbol: "ê",
    htmlNumber: "&#234;",
    htmlName: "&ecirc;",
    description: "Latin small letter e with circumflex",
    descriptionChinese: "带抑扬符的小写字母e",
  },
  {
    dec: 235,
    symbol: "ë",
    htmlNumber: "&#235;",
    htmlName: "&euml;",
    description: "Latin small letter e with diaeresis",
    descriptionChinese: "带分音符的小写字母e",
  },
  {
    dec: 236,
    symbol: "ì",
    htmlNumber: "&#236;",
    htmlName: "&igrave;",
    description: "Latin small letter i with grave",
    descriptionChinese: "带重音符的小写字母i",
  },
  {
    dec: 237,
    symbol: "í",
    htmlNumber: "&#237;",
    htmlName: "&iacute;",
    description: "Latin small letter i with acute",
    descriptionChinese: "带尖音符的小写字母i",
  },
  {
    dec: 238,
    symbol: "î",
    htmlNumber: "&#238;",
    htmlName: "&icirc;",
    description: "Latin small letter i with circumflex",
    descriptionChinese: "带抑扬符的小写字母i",
  },
  {
    dec: 239,
    symbol: "ï",
    htmlNumber: "&#239;",
    htmlName: "&iuml;",
    description: "Latin small letter i with diaeresis",
    descriptionChinese: "带分音符的小写字母i",
  },
  {
    dec: 240,
    symbol: "ð",
    htmlNumber: "&#240;",
    htmlName: "&eth;",
    description: "Latin small letter eth",
    descriptionChinese: "拉丁小写字母eth",
  },
  {
    dec: 241,
    symbol: "ñ",
    htmlNumber: "&#241;",
    htmlName: "&ntilde;",
    description: "Latin small letter n with tilde",
    descriptionChinese: "带波浪号的小写字母n",
  },
  {
    dec: 242,
    symbol: "ò",
    htmlNumber: "&#242;",
    htmlName: "&ograve;",
    description: "Latin small letter o with grave",
    descriptionChinese: "带重音符的小写字母o",
  },
  {
    dec: 243,
    symbol: "ó",
    htmlNumber: "&#243;",
    htmlName: "&oacute;",
    description: "Latin small letter o with acute",
    descriptionChinese: "带尖音符的小写字母o",
  },
  {
    dec: 244,
    symbol: "ô",
    htmlNumber: "&#244;",
    htmlName: "&ocirc;",
    description: "Latin small letter o with circumflex",
    descriptionChinese: "带抑扬符的小写字母o",
  },
  {
    dec: 245,
    symbol: "õ",
    htmlNumber: "&#245;",
    htmlName: "&otilde;",
    description: "Latin small letter o with tilde",
    descriptionChinese: "带波浪号的小写字母o",
  },
  {
    dec: 246,
    symbol: "ö",
    htmlNumber: "&#246;",
    htmlName: "&ouml;",
    description: "Latin small letter o with diaeresis",
    descriptionChinese: "带分音符的小写字母o",
  },
  {
    dec: 247,
    symbol: "÷",
    htmlNumber: "&#247;",
    htmlName: "&divide;",
    description: "Division sign",
    descriptionChinese: "除号",
  },
  {
    dec: 248,
    symbol: "ø",
    htmlNumber: "&#248;",
    htmlName: "&oslash;",
    description: "Latin small letter o with slash",
    descriptionChinese: "带斜杠的小写字母o",
  },
  {
    dec: 249,
    symbol: "ù",
    htmlNumber: "&#249;",
    htmlName: "&ugrave;",
    description: "Latin small letter u with grave",
    descriptionChinese: "带重音符的小写字母u",
  },
  {
    dec: 250,
    symbol: "ú",
    htmlNumber: "&#250;",
    htmlName: "&uacute;",
    description: "Latin small letter u with acute",
    descriptionChinese: "带尖音符的小写字母u",
  },
  {
    dec: 251,
    symbol: "û",
    htmlNumber: "&#251;",
    htmlName: "&ucirc;",
    description: "Latin small letter u with circumflex",
    descriptionChinese: "带抑扬符的小写字母u",
  },
  {
    dec: 252,
    symbol: "ü",
    htmlNumber: "&#252;",
    htmlName: "&uuml;",
    description: "Latin small letter u with diaeresis",
    descriptionChinese: "带分音符的小写字母u",
  },
  {
    dec: 253,
    symbol: "ý",
    htmlNumber: "&#253;",
    htmlName: "&yacute;",
    description: "Latin small letter y with acute",
    descriptionChinese: "带尖音符的小写字母y",
  },
  {
    dec: 254,
    symbol: "þ",
    htmlNumber: "&#254;",
    htmlName: "&thorn;",
    description: "Latin small letter thorn",
    descriptionChinese: "拉丁小写字母thorn",
  },
  {
    dec: 255,
    symbol: "ÿ",
    htmlNumber: "&#255;",
    htmlName: "&yuml;",
    description: "Latin small letter y with diaeresis",
    descriptionChinese: "带分音符的小写字母y",
  },
];

export type AsciiGroup = "control" | "printable" | "extended";

export const asciiItemBaseToAsciiItem = (base: AsciiItemBase): AsciiItem => {
  return {
    ...base,
    hex: base.dec.toString(16).padStart(2, "0").toUpperCase(),
    bin: base.dec.toString(2).padStart(8, "0"),
    oct: base.dec.toString(8).padStart(3, "0"),
    group:
      base.dec < 32 ? "control" : base.dec > 126 ? "extended" : "printable",
  };
};

export const asciiList = asciiListBase.map((e) => asciiItemBaseToAsciiItem(e));
