name: test-ssh
on:
  workflow_dispatch:
jobs:
  test-ssh:
    name: test-ssh
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: test remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          script: pm2 -v
